### ISSUE TITLE
Implement Business Handlers

### ISSUE THREAD

**Issue by bettkd** [zosimoGuardia/CostAnalytics#42]
##For @zosimoGuardia 
Implement Business Handlers Similar to `Dell.CostAnalytics.Business.Handlers.Measure.cs` for the following:
- [x] `Configuration.cs`
- [x] `Cost.cs`
- [x] `Iteration.cs`
- [x] `Phase.cs`
- [x] `Product.cs`
- [x] `Region.cs`
- [x] `SKU.cs`

- They should contain all the basic Add, Update, Delete, Get, and GetAll methods.
- They should also have conversion methods from Data Container to Business Container and vice versa
- For Business Container objects with members that are also objects (e.g` Iteration`), get the property from `CacheValues`

**Comment by bettkd** [comment]
#43 Implemented one other handlers (Iterations) Use these as examples

**Comment by zosimoGuardia** [comment]
Done. Classes implemented and pushed to Development branch.
