### ISSUE TITLE
Implement Method to Read Data to Database

### ISSUE THREAD

**Issue by bettkd** [zosimoGuardia/CostAnalytics#65]
Get latest pull #64.
 Complete the implementation of the `ReadData` method in `Dell.CostAnalytics.DataFactory.Parsers.FLCExtractParser`. Follow the example of `Region` for `Product`, `Configuration`, `Measure`, and `SKU`. `Cost` should be similar to `Iteration`.
Use the [Data Parser Flow Design.pdf](https://github.com/zosimoGuardia/CostAnalytics/files/980454/Data.Parser.Flow.Design.pdf) as a guide.

Note: _Regex_ may be required to get `Product.Variant` etc. Need to sync up later on data source for `Phase` and how to handle parsing for that.

**Comment by zosimoGuardia** [comment]
Finished implementing the class. Won't close the issue yet because there are some things I'm not certain about. I commented them so we can talk about them next week.

**Comment by bettkd** [comment]
Cool, we'll talk about it next week

**Comment by bettkd** [comment]
You can close the issue once unit test passes
