### ISSUE TITLE
Audit Events Data/Business Modeling

### ISSUE THREAD

**Issue by bettkd** [zosimoGuardia/CostAnalytics#96]
#### * AuditEvent
| -ID
| -EnumEventID
| -Message
| -TimeStamp
| -UserID

Actions:
> Create standard Stored Procedures for this table (Add, Update, Delete, Get, GetAll)
> Create corresponding Data and Business Layer Containers and Handlers
> PS: Default userID will be -1 until we implement User Model

#### * EnumEvent
| -ID
| -EventCode
| -Description

Actions:
> NO need to create any Stored Procedures for this table, Enum data will be entered into DB manually
> @bettkd will create an Enum class on Business Layer with info. corresponding to ones on the DB

#### * User
| -ID
| -UserName

Actions:
> Create standard Stored Procedures for this table (Add, Update, Delete, Get, GetAll)
> Create corresponding Data and Business Layer Containers and Handlers
> User Model will be implemented at the application level. We will leverage Windows Auth as discussed

**Comment by zosimoGuardia** [comment]
Done. Everything compiles, but haven't unit tested yet.
